import supabase from "../../services/supabase";

/**
 * Send an invoice PDF to the guest via a Supabase Edge Function.
 *
 * This is fire-and-forget — it never blocks the caller.
 * If the email fails, the error is logged but not thrown,
 * so the core action (checkout) always succeeds.
 *
 * @param {number}  bookingId - The booking ID
 * @param {Blob}    pdfBlob   - The PDF blob generated by useGenerateInvoice
 * @param {string}  guestEmail - Recipient email address
 */
export async function sendInvoiceEmail(bookingId, pdfBlob, guestEmail) {
  // Guard: skip if no guest email
  if (!guestEmail) {
    console.warn(
      `sendInvoiceEmail: No email for booking #${bookingId}, skipping`,
    );
    return;
  }

  try {
    // Convert the PDF Blob to an ArrayBuffer for transport
    const arrayBuffer = await pdfBlob.arrayBuffer();
    const pdfBytes = new Uint8Array(arrayBuffer);

    // Call the Supabase Edge Function with the PDF and metadata
    const { error } = await supabase.functions.invoke("send-invoice", {
      body: {
        bookingId,
        recipientEmail: guestEmail,
        pdfBase64: btoa(
          pdfBytes.reduce((data, byte) => data + String.fromCharCode(byte), ""),
        ),
      },
    });

    if (error) {
      console.error(`sendInvoiceEmail: Edge Function error:`, error);
    } else {
      console.log(`sendInvoiceEmail: Invoice sent for booking #${bookingId}`);
    }
  } catch (err) {
    // Fire-and-forget: log but never throw
    console.error(
      `sendInvoiceEmail: Failed for booking #${bookingId}:`,
      err,
    );
  }
}
